chore-add-tests
nilenso/shahns-onboarding pull request #3
Opened 2023-04-20 12:53 UTC by shahn95

2023-04-25 09:32 UTC, shhivam requested changes

2023-04-25 09:32 UTC, shhivam commented on mars-rover-new/src/mars_rover_new/core.clj
> +    (truthy (and count-test x y (> x 0) (> y 0)))))
Please leave a comment explaining why you had to return a boolean value and why returning a `nil` wouldn't have worked.

2023-04-25 09:32 UTC, shhivam commented on mars-rover-new/src/mars_rover_new/core.clj
An overall comment for the file: you should move the constants towards the start of the file. That way you won't have to `declare` anything beforehand.

Also, consider looking into `defonce`

2023-04-25 09:32 UTC, shhivam commented on mars-rover-new/src/mars_rover_new/core.clj
> +                 :move {"N" {:coord :y
[NAMING]
re: `:coord` -- Is `:y` really a coordinate?

2023-04-25 09:32 UTC, shhivam commented on mars-rover-new/src/mars_rover_new/core.clj
> +(def fn-map {"L" mars-rover-new.core/rotate-left
Consider renaming `fn-map`, the comment explains it pretty well but strive to name functions which are self explanatory.

2023-04-25 09:32 UTC, shhivam commented on mars-rover-new/src/mars_rover_new/core.clj
> +(def fn-map {"L" mars-rover-new.core/rotate-left
Something like `command->fn` or `action->fn`

2023-04-25 09:32 UTC, shhivam commented on mars-rover-new/src/mars_rover_new/core.clj
> +  (display-result (process-cmds (process-user-input))))
[NITPICK]
Can we make this particular line more readable?

2023-04-25 09:32 UTC, shhivam commented on mars-rover-new/test/mars_rover_new/core_test.clj
> +      false (valid-cmd-sequence? "5.2 10"))))
Good use of `are`

2023-04-25 09:32 UTC, shhivam commented on mars-rover-new/test/mars_rover_new/core_test.clj
Tests look good!

2023-04-25 09:32 UTC, shhivam commented on mars-rover-new/src/mars_rover_new/core.clj
> +    (if (and (in-range? x 0 max-x) (in-range? y 0 max-y))
Consider moving this logic outside somewhere else.
Generally `display-result` should be a "dumb" function which assumes that whatever we pass to it is correct.

This loops into the Single Responsibility Principle.

2023-04-25 09:32 UTC, shhivam commented on mars-rover-new/src/mars_rover_new/core.clj
> +  (reduce (fn [new-mars-rover-data cmd] ((get fn-map cmd) new-mars-rover-data))
Is there any other way we can use here instead of a `reduce`?

2023-05-03 10:05 UTC, shahn95 commented on mars-rover-new/src/mars_rover_new/core.clj
Yes, already done, this version doesn't use `declare` since constants are all `def`'ed before usage.

`defonce` looks interesting. This would be a replacement for `def` when declaring my constants, right?
I read that this is useful when we're hot reloading and we want to maintain state between reloads.

2023-05-22 12:14 UTC, shahn95 commented on mars-rover-new/src/mars_rover_new/core.clj
Just realized that `defonce` is def + once, which makes a lot of sense. Was reading it as _defaunce_ before I realized this.

2023-05-22 12:14 UTC, shahn95 commented on mars-rover-new/src/mars_rover_new/core.clj
> +                 :move {"N" {:coord :y
You are correct, y is an ordinate, not co-ordinate, updated `:coord` to `:ord` in branch `feature-movement-functions`.

2023-05-22 12:14 UTC, shahn95 commented on mars-rover-new/src/mars_rover_new/core.clj
> +    (truthy (and count-test x y (> x 0) (> y 0)))))
Yes, I've added a comment explaining this.

2023-05-22 12:14 UTC, shahn95 commented on mars-rover-new/src/mars_rover_new/core.clj
> +(def fn-map {"L" mars-rover-new.core/rotate-left
Agreed. I like `command->fn`, I've changed it to `cmd->fn` since I'm using `cmd` in other parts of my code as well.

Updated on branch: `feature-movement-functions`

2023-05-22 12:14 UTC, shahn95 commented on mars-rover-new/src/mars_rover_new/core.clj
> +  (display-result (process-cmds (process-user-input))))
Yes, I changed this to use the threading macro.

2023-05-22 12:14 UTC, shahn95 commented on mars-rover-new/src/mars_rover_new/core.clj
> +    (if (and (in-range? x 0 max-x) (in-range? y 0 max-y))
Agreed, good point. I've moved this logic out into a separate function. Change is on branch `feature-movement-functions`

2023-05-22 12:14 UTC, shahn95 commented on mars-rover-new/src/mars_rover_new/core.clj
> +  (reduce (fn [new-mars-rover-data cmd] ((get fn-map cmd) new-mars-rover-data))
`reduce` seemed like a good way to do this since each successive move depends on the updated state.

2023-05-22 12:14 UTC, shahn95 commented on mars-rover-new/src/mars_rover_new/core.clj
> +  (reduce (fn [new-mars-rover-data cmd] ((get fn-map cmd) new-mars-rover-data))
We could perhaps implement a recursive function to do the movements recursively on the returned updated states.

2023-05-22 13:02 UTC, shhivam approved these changes
Approved since the requested changes were made in the parent branch (`feature-movement-functions`)

2023-05-22 13:04 UTC, shhivam commented on mars-rover-new/src/mars_rover_new/core.clj
> +  (reduce (fn [new-mars-rover-data cmd] ((get fn-map cmd) new-mars-rover-data))
Making a note of this to discuss later

2023-05-22 13:22 UTC, merged